name = "test.decimals.url"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "test.decimals.url_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "test.decimals.url.wasm"
command = "npm run build:release"
